server:
  forward-headers-strategy: framework
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 950311721021-tgmram31ad1e3tgr3brlq8abe1mk7pvh.apps.googleusercontent.com
            client-secret: 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
#            redirect-uri: https://{baseHost}{basePort}{basePath}/login/oauth2/code/google
#            client-id: 950311721021-7fkrjsilkflo0ltjbao7vqnbp7ai310d.apps.googleusercontent.com
#            client-secret: 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

