
apiVersion: v1
kind: Namespace
metadata:
  name: production-database
---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast
  namespace: production-database
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
  fstype: ext4
volumeBindingMode: Immediate
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: normal
  namespace: production-database
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-balanced
  fstype: ext4
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-groovv-production-database
  namespace: production-database
spec:
  storageClassName: fast
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-groovv-production-database-backups
  namespace: production-database
spec:
  storageClassName: normal
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
