apiVersion: apps/v1
kind: Deployment
metadata:
  name: groovv-io
spec:
  replicas: 3
  selector:
    matchLabels:
      app: groovv-io
  template:
    metadata:
      labels:
        app: groovv-io
    spec:
      containers:
        - name: groovv-io
          image: us-docker.pkg.dev/groovv-cloud/groovv-containers/groovv.io:1.0
          imagePullPolicy: Always
          livenessProbe:
            periodSeconds: 10
            initialDelaySeconds: 10
            httpGet:
              port: 8080
              path: /login
          ports:
            - containerPort: 8080


